"""add kyb_data to company_profiles

Revision ID: 01380f66d0d7
Revises: 8b5bfe2f5de8
Create Date: 2026-02-26 22:54:59.631205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01380f66d0d7'
down_revision: Union[str, Sequence[str], None] = '8b5bfe2f5de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profiles', sa.Column('kyb_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_profiles', 'kyb_data')
    # ### end Alembic commands ###
